# Generated by Django 4.2.2 on 2023-06-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_inspiration', to='craftapi.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftapi.project')),
            ],
        ),
    ]
