# Generated by Django 4.2.2 on 2023-06-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pattern_url',
            new_name='pattern_url',
        ),
    ]
