# Generated by Django 4.2.2 on 2023-06-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftapi', '0002_inspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inspirations',
            field=models.ManyToManyField(through='craftapi.Inspiration', to='craftapi.project'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='inspiration_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_inspirations', to='craftapi.project'),
        ),
        migrations.AddConstraint(
            model_name='inspiration',
            constraint=models.CheckConstraint(check=models.Q(('project', models.F('inspiration_project')), _negated=True), name='not_same'),
        ),
    ]
