# Generated by Django 4.2.2 on 2023-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapi', '0002_rename_patternurl_project_pattern_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pattern_url',
            field=models.URLField(blank=True),
        ),
    ]
